### PR TITLE
Function solution to assign manager to mgnr column based on date

### PR DESCRIPTION
**Pull request by p-will-b**
Hey Ryan,

Thanks for your cool post. I believe I've got a workable solution for you to obviate the for loop.  The one issue with this solution is that it doesn't quite get the Evans & Houllier era correct. I think that could be 
solved by reassigning dates as such:

fix Evans + Houllier era

mngrs_clean[mngrs_clean$Name == "Evans", "To"] <- "1998-07-15"

mngrs_clean[mngrs_clean$Name == "Houllier", "From"] <- "1998-11-13"

Otherwise all the code appears to work. I haven't fully checked for bugs...let me know if this doesn't work for you.

Summary of changes: 

1) add date_int column to mngrs_clean to define date interval
2) use purrr::walk to look at each interval and assign it to mgnr column

library(lubridate)
library(purrr)
....
### Convert classes
mngrs_clean <- mngrs_clean %>%
  mutate_at(vars(From:To), funs(ymd)) %>% 
  mutate(To = if_else(row_number() == nrow(mngrs_clean), Sys.Date(), To)) %>% 
  mutate(date_int = lubridate::interval(From, To))
....

lfc <- as.tibble(england) %>%
  mutate(Date = ymd(Date)) %>% 
  mutate_at(vars(home:FT, result), funs(as.character)) %>%
  mutate_at(vars(hgoal:goaldif), funs(as.numeric)) %>%
  filter(home == "Liverpool" | visitor == "Liverpool") %>% 
  mutate(at_anf = "", 
         at_anf = ifelse(home == "Liverpool", "Anfield", "Away")) %>%
  mutate(mngr = "") %>% 
  select(Date, home, visitor, FT, result, at_anf, mngr) %>% 
  arrange(Date)

### Walk through mngrs_clean date intervals and assign to lfc$mngr
purrr::walk(1:nrow(mngrs_clean), ~ (lfc$mngr[lfc$Date %within% mngrs_clean$date_int[.x]] <<- mngrs_clean$Name[.x]))

### CODE REVIEW

**Comment by restrellado** [comment]
Thank you so much for taking the time! I can't wait to dig into this. I'm working on a follow-up post so this came just in time. I'll respond back here if I have any questions.

**Comment by p-will-b** [comment]
Cheers and of course. Let me know if you find any improvements or other issues. I look forward to the update.

**Comment by restrellado** [comment]
Wow, that worked great! Thank you again! I hadn't even noticed the Houllier/Evans date problem in the first version. Question for you to make sure I'm understanding correctly: We use `<<-` because we're changing an element of a vector that is outside the function?

**Comment by p-will-b** [comment]
The way I understand it is that because the variable already exists we use it to reassign.  The help file for ?"<<-" describes it thus: "The operators <<- and ->> are normally only used in functions, and cause a search to made through parent environments for an existing definition of the variable being assigned."

**Comment by p-will-b** [comment]
Here is another (sub-optimal) solution:

map_df(1:nrow(mngrs_clean), ~ lfc %>% 
                 mutate(mngr = case_when(
                   Date %within% mngrs_clean$date_int[.x] ~ mngrs_clean$Name[.x]))) %>% 
  filter(!is.na(.$mngr))

The problem here is that it creates a lot of unnecessary NA `mngr` rows which are filtered out at the end. Consequently, this code is much slower. Another thing is that the original solution preserves the row count at 4499. This solution produces a dataframe with only 4483 rows. My guess is that it has to do with the date intervals and %within%, but I didn't check. Just wanted to make you aware of this possibility as you might refine it.

**Pull request closed without merging**
